### PR TITLE
Fallout 4 VR support

### LINKED ISSUE #206: Add support for Fallout 4 VR edition
The modding behaves excactly as Fallout 4 with the exception that the directory for plugins.txt is different and the .exe file has a new name, so hopefully this should not require a lot of code additions.

### PR DESCRIPTION
**Pull request by squid-box**
Hoping to resolve #206 with this.

It's not a super clean solution, but without reworking the website / NMM links, I don't see how to do it otherwise. I've cloned what I think is the minimum viable game mode from Fallout 4 to Fallout 4 VR (I tried referencing Fallout 4 parts when possible, to keep additions to a minimum). 

The bad part is how I try to determine the game mode for a mod grabbed through an _nxm://_ link (see _NexusClient/Bootstrapper.cs : DetermineRequestedGameMode_), it will rewrite mods pointing to Fallout 4 to Fallout 4 VR if _RememberedGameMode_ is set to _Fallout4VR_.

As a disclaimer, I've not been able to find the dev documentation from the Readme, so it's been a lot of fumbling in the dark.

### CODE REVIEW

File: Fallout4VR/Fallout4VRGameModeDescriptor.cs [hunk 1]
```diff
@@ -10,8 +10,8 @@ public class Fallout4VRGameModeDescriptor : GamebryoGameModeDescriptorBase
 	{
 		private static string[] EXECUTABLES = { "Fallout4VR.exe" };
 		private static string[] CRITICAL_PLUGINS = { "Fallout4.esm", "Fallout4_VR.esm" };
-		private static string[] OFFICIAL_PLUGINS = { };
-        private static string[] OFFICIAL_UNMANAGED_PLUGINS = { };
+        private static string[] OFFICIAL_PLUGINS = { "DLCRobot.esm", "DLCworkshop01.esm", "DLCCoast.esm", "DLCworkshop02.esm", "DLCworkshop03.esm", "DLCNukaWorld.esm" };
```
Comment (squid-box) [inline Fallout4VR/Fallout4VRGameModeDescriptor.cs]: On second thought, this might not be entirely correct? Technically these aren't official plugins for Fallout 4 VR, and NMM will still handle the files if they're put in the FO4VR data folder. ¯\_(ツ)_/¯

**Comment by squid-box** [comment]
Unnecessary amount of commits, but I'll keep this branch as is for this PR now and do any follow-up on a separate branch instead.

**Comment by Kisaragi55** [comment]
the nmm report is: login error: cannot reach the nexus login server.Either your firewall is blocking nmm or the login server is down.
But my firewall have the NMM with an exception and i dont know happened, please help when you can
